......................
----------------------------------------------------------------------
Ran 22 tests in 0.002s

OK
[W1020 02:05:50.375353836 socket.cpp:767] [c10d] The IPv6 network addresses of (dummy_endpoint, 29400) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
[W1020 02:05:51.166750570 socket.cpp:767] [c10d] The IPv6 network addresses of (dummy_endpoint, 29400) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
[W1020 02:05:52.910120203 socket.cpp:767] [c10d] The IPv6 network addresses of (dummy_endpoint, 29400) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
[W1020 02:05:53.599859119 socket.cpp:767] [c10d] The IPv6 network addresses of (dummy_endpoint, 29400) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
[W1020 02:05:54.551779761 socket.cpp:767] [c10d] The IPv6 network addresses of (dummy_endpoint, 29400) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
[W1020 02:05:57.021149844 socket.cpp:767] [c10d] The IPv6 network addresses of (dummy_endpoint, 29400) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
[W1020 02:05:59.041141767 socket.cpp:767] [c10d] The IPv6 network addresses of (dummy_endpoint, 29400) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
[E1020 02:05:59.041148782 socket.cpp:1031] [c10d] The client socket has timed out after 10000ms while trying to connect to (dummy_endpoint, 29400).
[W1020 02:05:59.041811648 TCPStore.cpp:340] [c10d] TCP client failed to connect/validate to host dummy_endpoint:29400 - retrying (try=0, timeout=10000ms, delay=9560ms): The client socket has timed out after 10000ms while trying to connect to (dummy_endpoint, 29400).
Exception raised from throwTimeoutError at /home/jenkins/actions-runner/_work/torch-xpu-ops/torch-xpu-ops/pytorch/torch/csrc/distributed/c10d/socket.cpp:1033 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7f62e8170fe8 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x14a21c5 (0x7f62c92031c5 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0x690409c (0x7f62ce66509c in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x6904271 (0x7f62ce665271 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x690467b (0x7f62ce66567b in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x686f007 (0x7f62ce5d0007 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::TCPStore::TCPStore(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10d::TCPStoreOptions const&) + 0x47c (0x7f62ce5d381c in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0xee966d (0x7f62dd7a266d in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x43293b (0x7f62dcceb93b in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #15: <unknown function> + 0x42fedb (0x7f62dcce8edb in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)

[W1020 02:06:08.664888697 socket.cpp:767] [c10d] The IPv6 network addresses of (dummy_endpoint, 29400) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
[W1020 02:06:17.850618266 socket.cpp:767] [c10d] The IPv6 network addresses of (dummy_endpoint, 29400) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
[E1020 02:06:17.850636617 socket.cpp:1031] [c10d] The client socket has timed out after 10000ms while trying to connect to (dummy_endpoint, 29400).
[E1020 02:06:17.850707630 TCPStore.cpp:328] [c10d] TCP client failed to connect/validate to host dummy_endpoint:29400 - timed out (try=1, timeout=10000ms): The client socket has timed out after 10000ms while trying to connect to (dummy_endpoint, 29400).
Exception raised from throwTimeoutError at /home/jenkins/actions-runner/_work/torch-xpu-ops/torch-xpu-ops/pytorch/torch/csrc/distributed/c10d/socket.cpp:1033 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7f62e8170fe8 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x14a21c5 (0x7f62c92031c5 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0x690409c (0x7f62ce66509c in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x6904271 (0x7f62ce665271 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x690467b (0x7f62ce66567b in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x686f007 (0x7f62ce5d0007 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::TCPStore::TCPStore(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10d::TCPStoreOptions const&) + 0x47c (0x7f62ce5d381c in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0xee966d (0x7f62dd7a266d in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x43293b (0x7f62dcceb93b in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #15: <unknown function> + 0x42fedb (0x7f62dcce8edb in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)

[W1020 02:06:17.893874306 socket.cpp:767] [c10d] The IPv6 network addresses of (dummy_endpoint, 29400) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
[W1020 02:06:17.271654046 socket.cpp:767] [c10d] The IPv6 network addresses of (dummy_endpoint, 29400) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
[W1020 02:06:18.977340254 socket.cpp:767] [c10d] The IPv6 network addresses of (dummy_endpoint, 29400) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
[W1020 02:06:19.927418676 socket.cpp:767] [c10d] The IPv6 network addresses of (dummy_endpoint, 29400) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
[W1020 02:06:21.970723022 socket.cpp:767] [c10d] The IPv6 network addresses of (dummy_endpoint, 29400) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
[W1020 02:06:23.525746427 socket.cpp:767] [c10d] The IPv6 network addresses of (dummy_endpoint, 29400) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
[E1020 02:06:23.525764049 socket.cpp:1031] [c10d] The client socket has timed out after 10000ms while trying to connect to (dummy_endpoint, 29400).
[W1020 02:06:23.525818622 TCPStore.cpp:340] [c10d] TCP client failed to connect/validate to host dummy_endpoint:29400 - retrying (try=0, timeout=10000ms, delay=4808ms): The client socket has timed out after 10000ms while trying to connect to (dummy_endpoint, 29400).
Exception raised from throwTimeoutError at /home/jenkins/actions-runner/_work/torch-xpu-ops/torch-xpu-ops/pytorch/torch/csrc/distributed/c10d/socket.cpp:1033 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7f62e8170fe8 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x14a21c5 (0x7f62c92031c5 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0x690409c (0x7f62ce66509c in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x6904271 (0x7f62ce665271 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x690467b (0x7f62ce66567b in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x686f007 (0x7f62ce5d0007 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::TCPStore::TCPStore(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10d::TCPStoreOptions const&) + 0x47c (0x7f62ce5d381c in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0xee966d (0x7f62dd7a266d in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x43293b (0x7f62dcceb93b in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #15: <unknown function> + 0x42fedb (0x7f62dcce8edb in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)

[W1020 02:06:28.360258004 socket.cpp:767] [c10d] The IPv6 network addresses of (dummy_endpoint, 29400) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
[W1020 02:06:37.142681241 socket.cpp:767] [c10d] The IPv6 network addresses of (dummy_endpoint, 29400) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
[E1020 02:06:37.142697999 socket.cpp:1031] [c10d] The client socket has timed out after 10000ms while trying to connect to (dummy_endpoint, 29400).
[E1020 02:06:37.142752709 TCPStore.cpp:328] [c10d] TCP client failed to connect/validate to host dummy_endpoint:29400 - timed out (try=1, timeout=10000ms): The client socket has timed out after 10000ms while trying to connect to (dummy_endpoint, 29400).
Exception raised from throwTimeoutError at /home/jenkins/actions-runner/_work/torch-xpu-ops/torch-xpu-ops/pytorch/torch/csrc/distributed/c10d/socket.cpp:1033 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7f62e8170fe8 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x14a21c5 (0x7f62c92031c5 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0x690409c (0x7f62ce66509c in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x6904271 (0x7f62ce665271 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x690467b (0x7f62ce66567b in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x686f007 (0x7f62ce5d0007 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::TCPStore::TCPStore(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10d::TCPStoreOptions const&) + 0x47c (0x7f62ce5d381c in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0xee966d (0x7f62dd7a266d in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x43293b (0x7f62dcceb93b in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #15: <unknown function> + 0x42fedb (0x7f62dcce8edb in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)

...[E1020 02:06:38.156304354 socket.cpp:1031] [c10d] The client socket has timed out after 2000ms while trying to connect to (localhost, 40237).
[W1020 02:06:38.156372428 TCPStore.cpp:340] [c10d] TCP client failed to connect/validate to host localhost:40237 - retrying (try=0, timeout=2000ms, delay=1883ms): The client socket has timed out after 2000ms while trying to connect to (localhost, 40237).
Exception raised from throwTimeoutError at /home/jenkins/actions-runner/_work/torch-xpu-ops/torch-xpu-ops/pytorch/torch/csrc/distributed/c10d/socket.cpp:1033 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7f62e8170fe8 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x14a21c5 (0x7f62c92031c5 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0x690409c (0x7f62ce66509c in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x6904271 (0x7f62ce665271 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x690467b (0x7f62ce66567b in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x686f007 (0x7f62ce5d0007 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::TCPStore::TCPStore(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10d::TCPStoreOptions const&) + 0x47c (0x7f62ce5d381c in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0xee966d (0x7f62dd7a266d in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x43293b (0x7f62dcceb93b in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #15: <unknown function> + 0x42fedb (0x7f62dcce8edb in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)

[E1020 02:06:40.043305782 socket.cpp:1031] [c10d] The client socket has timed out after 2000ms while trying to connect to (localhost, 40237).
[E1020 02:06:40.043373350 TCPStore.cpp:328] [c10d] TCP client failed to connect/validate to host localhost:40237 - timed out (try=1, timeout=2000ms): The client socket has timed out after 2000ms while trying to connect to (localhost, 40237).
Exception raised from throwTimeoutError at /home/jenkins/actions-runner/_work/torch-xpu-ops/torch-xpu-ops/pytorch/torch/csrc/distributed/c10d/socket.cpp:1033 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7f62e8170fe8 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x14a21c5 (0x7f62c92031c5 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0x690409c (0x7f62ce66509c in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x6904271 (0x7f62ce665271 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x690467b (0x7f62ce66567b in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x686f007 (0x7f62ce5d0007 in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::TCPStore::TCPStore(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10d::TCPStoreOptions const&) + 0x47c (0x7f62ce5d381c in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0xee966d (0x7f62dd7a266d in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x43293b (0x7f62dcceb93b in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #15: <unknown function> + 0x42fedb (0x7f62dcce8edb in /home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/lib/libtorch_python.so)

...........................
----------------------------------------------------------------------
Ran 30 tests in 49.740s

OK
....................................W1020 02:06:42.173000 2344730 site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:1342] The node 'this_node_1_1' has failed to send a keep-alive heartbeat to the rendezvous 'dummy_run_id' due to an error of type RendezvousTimeoutError.
.W1020 02:06:42.174000 2344730 site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:1342] The node 'this_node_1_1' has failed to send a keep-alive heartbeat to the rendezvous 'dummy_run_id' due to an error of type RendezvousError.
...................W1020 02:06:44.549000 2344730 site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py:1293] The node 'this_node_1_1' has failed to shutdown the rendezvous 'dummy_run_id' due to an error of type RendezvousError.
.........................................
----------------------------------------------------------------------
Ran 97 tests in 27.809s

OK
.../home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/etcd/client.py:954: DeprecationWarning: HTTPResponse.getheader() is deprecated and will be removed in urllib3 v2.6.0. Instead use HTTPResponse.headers.get(name, default).
  cluster_id = response.getheader("x-etcd-cluster-id")
/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/etcd/__init__.py:62: DeprecationWarning: HTTPResponse.getheaders() is deprecated and will be removed in urllib3 v2.6.0. Instead access HTTPResponse.headers directly.
  headers = response.getheaders()
..../home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/etcd/client.py:954: DeprecationWarning: HTTPResponse.getheader() is deprecated and will be removed in urllib3 v2.6.0. Instead use HTTPResponse.headers.get(name, default).
  cluster_id = response.getheader("x-etcd-cluster-id")
/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/etcd/__init__.py:62: DeprecationWarning: HTTPResponse.getheaders() is deprecated and will be removed in urllib3 v2.6.0. Instead access HTTPResponse.headers directly.
  headers = response.getheaders()
........
----------------------------------------------------------------------
Ran 15 tests in 4.170s

OK
2025-10-20 02:07:17.302012 I | etcdmain: etcd Version: 3.3.25
2025-10-20 02:07:17.302046 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
2025-10-20 02:07:17.302048 I | etcdmain: Go Version: go1.18.1
2025-10-20 02:07:17.302050 I | etcdmain: Go OS/Arch: linux/amd64
2025-10-20 02:07:17.302052 I | etcdmain: setting maximum number of CPUs to 192, total number of available CPUs is 192
2025-10-20 02:07:17.304498 I | embed: listening for peers on http://localhost:50699
2025-10-20 02:07:17.304989 I | embed: listening for client requests on localhost:36445
2025-10-20 02:07:17.305053 W | pkg/fileutil: check file permission: directory "/tmp/torchelastic_etcd_datasv8c80kt/0" exist, but the permission is "drwxrwxr-x". The recommended permission is "-rwx------" to prevent possible unprivileged access to the data.
2025-10-20 02:07:17.307406 I | etcdserver: name = default
2025-10-20 02:07:17.307409 I | etcdserver: data dir = /tmp/torchelastic_etcd_datasv8c80kt/0
2025-10-20 02:07:17.307411 I | etcdserver: member dir = /tmp/torchelastic_etcd_datasv8c80kt/0/member
2025-10-20 02:07:17.307413 I | etcdserver: heartbeat = 100ms
2025-10-20 02:07:17.307414 I | etcdserver: election = 1000ms
2025-10-20 02:07:17.307416 I | etcdserver: snapshot count = 100000
2025-10-20 02:07:17.307544 I | etcdserver: advertise client URLs = http://localhost:36445
2025-10-20 02:07:17.307546 I | etcdserver: initial advertise peer URLs = http://localhost:2380
2025-10-20 02:07:17.307552 I | etcdserver: initial cluster = default=http://localhost:2380
2025-10-20 02:07:17.309146 I | etcdserver: starting member 8e9e05c52164694d in cluster cdf818194e3a8c32
2025-10-20 02:07:17.309165 I | raft: 8e9e05c52164694d became follower at term 0
2025-10-20 02:07:17.309170 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2025-10-20 02:07:17.309173 I | raft: 8e9e05c52164694d became follower at term 1
2025-10-20 02:07:17.310324 W | auth: simple token is not cryptographically signed
2025-10-20 02:07:17.312081 I | etcdserver: starting server... [version: 3.3.25, cluster version: to_be_decided]
2025-10-20 02:07:17.312120 I | etcdserver: 8e9e05c52164694d as single-node; fast-forwarding 9 ticks (election ticks 10)
2025-10-20 02:07:17.312376 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
2025-10-20 02:07:17.409693 I | raft: 8e9e05c52164694d is starting a new election at term 1
2025-10-20 02:07:17.409745 I | raft: 8e9e05c52164694d became candidate at term 2
2025-10-20 02:07:17.409753 I | raft: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 2
2025-10-20 02:07:17.409758 I | raft: 8e9e05c52164694d became leader at term 2
2025-10-20 02:07:17.409760 I | raft: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 2
2025-10-20 02:07:17.409959 I | embed: ready to serve client requests
2025-10-20 02:07:17.410154 I | etcdserver: published {Name:default ClientURLs:[http://localhost:36445]} to cluster cdf818194e3a8c32
2025-10-20 02:07:17.410186 I | etcdserver: setting up the initial cluster version to 3.3
2025-10-20 02:07:17.410229 E | etcdmain: forgot to set Type=notify in systemd service file?
2025-10-20 02:07:17.410316 N | etcdserver/membership: set the initial cluster version to 3.3
2025-10-20 02:07:17.410354 I | etcdserver/api: enabled capabilities for version 3.3
2025-10-20 02:07:17.410494 N | embed: serving insecure client requests on 127.0.0.1:36445, this is strongly discouraged!
INFO 2025-10-20 02:07:18,298 Etcd machines: ['http://localhost:36445']
/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/etcd/client.py:954: DeprecationWarning: HTTPResponse.getheader() is deprecated and will be removed in urllib3 v2.6.0. Instead use HTTPResponse.headers.get(name, default).
  cluster_id = response.getheader("x-etcd-cluster-id")
/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/etcd/__init__.py:62: DeprecationWarning: HTTPResponse.getheaders() is deprecated and will be removed in urllib3 v2.6.0. Instead access HTTPResponse.headers directly.
  headers = response.getheaders()
.INFO 2025-10-20 02:07:18,302 Etcd machines: ['http://localhost:36445']
.INFO 2025-10-20 02:07:18,306 Etcd machines: ['http://localhost:36445']
.2025-10-20 02:07:18.309174 N | pkg/osutil: received terminated signal, shutting down...
2025-10-20 02:07:18.309227 I | etcdserver: skipped leadership transfer for single member cluster

----------------------------------------------------------------------
Ran 3 tests in 1.018s

OK
2025-10-20 02:07:19.691602 I | etcdmain: etcd Version: 3.3.25
2025-10-20 02:07:19.691634 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
2025-10-20 02:07:19.691636 I | etcdmain: Go Version: go1.18.1
2025-10-20 02:07:19.691638 I | etcdmain: Go OS/Arch: linux/amd64
2025-10-20 02:07:19.691641 I | etcdmain: setting maximum number of CPUs to 192, total number of available CPUs is 192
2025-10-20 02:07:19.691950 I | embed: listening for peers on http://localhost:45547
2025-10-20 02:07:19.691980 I | embed: listening for client requests on localhost:39615
2025-10-20 02:07:19.692014 W | pkg/fileutil: check file permission: directory "/tmp/torchelastic_etcd_datawpap24vy/0" exist, but the permission is "drwxrwxr-x". The recommended permission is "-rwx------" to prevent possible unprivileged access to the data.
2025-10-20 02:07:19.694406 I | etcdserver: name = default
2025-10-20 02:07:19.694409 I | etcdserver: data dir = /tmp/torchelastic_etcd_datawpap24vy/0
2025-10-20 02:07:19.694411 I | etcdserver: member dir = /tmp/torchelastic_etcd_datawpap24vy/0/member
2025-10-20 02:07:19.694413 I | etcdserver: heartbeat = 100ms
2025-10-20 02:07:19.694414 I | etcdserver: election = 1000ms
2025-10-20 02:07:19.694416 I | etcdserver: snapshot count = 100000
2025-10-20 02:07:19.694523 I | etcdserver: advertise client URLs = http://localhost:39615
2025-10-20 02:07:19.694525 I | etcdserver: initial advertise peer URLs = http://localhost:2380
2025-10-20 02:07:19.694536 I | etcdserver: initial cluster = default=http://localhost:2380
2025-10-20 02:07:19.696206 I | etcdserver: starting member 8e9e05c52164694d in cluster cdf818194e3a8c32
2025-10-20 02:07:19.696219 I | raft: 8e9e05c52164694d became follower at term 0
2025-10-20 02:07:19.696223 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2025-10-20 02:07:19.696225 I | raft: 8e9e05c52164694d became follower at term 1
2025-10-20 02:07:19.697410 W | auth: simple token is not cryptographically signed
2025-10-20 02:07:19.699324 I | etcdserver: starting server... [version: 3.3.25, cluster version: to_be_decided]
2025-10-20 02:07:19.699399 I | etcdserver: 8e9e05c52164694d as single-node; fast-forwarding 9 ticks (election ticks 10)
2025-10-20 02:07:19.699612 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
2025-10-20 02:07:19.896333 I | raft: 8e9e05c52164694d is starting a new election at term 1
2025-10-20 02:07:19.896379 I | raft: 8e9e05c52164694d became candidate at term 2
2025-10-20 02:07:19.896388 I | raft: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 2
2025-10-20 02:07:19.896393 I | raft: 8e9e05c52164694d became leader at term 2
2025-10-20 02:07:19.896396 I | raft: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 2
2025-10-20 02:07:19.896643 I | etcdserver: published {Name:default ClientURLs:[http://localhost:39615]} to cluster cdf818194e3a8c32
2025-10-20 02:07:19.896671 I | etcdserver: setting up the initial cluster version to 3.3
2025-10-20 02:07:19.896693 I | embed: ready to serve client requests
2025-10-20 02:07:19.896831 E | etcdmain: forgot to set Type=notify in systemd service file?
2025-10-20 02:07:19.896912 N | etcdserver/membership: set the initial cluster version to 3.3
2025-10-20 02:07:19.896950 I | etcdserver/api: enabled capabilities for version 3.3
2025-10-20 02:07:19.897071 N | embed: serving insecure client requests on 127.0.0.1:39615, this is strongly discouraged!
2025-10-20 02:07:20.686287 N | pkg/osutil: received terminated signal, shutting down...
2025-10-20 02:07:20.686376 I | etcdserver: skipped leadership transfer for single member cluster
.2025-10-20 02:07:20.699989 I | etcdmain: etcd Version: 3.3.25
2025-10-20 02:07:20.700027 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
2025-10-20 02:07:20.700030 I | etcdmain: Go Version: go1.18.1
2025-10-20 02:07:20.700032 I | etcdmain: Go OS/Arch: linux/amd64
2025-10-20 02:07:20.700034 I | etcdmain: setting maximum number of CPUs to 192, total number of available CPUs is 192
2025-10-20 02:07:20.700450 I | embed: listening for peers on http://localhost:40541
2025-10-20 02:07:20.700489 I | embed: listening for client requests on localhost:47051
2025-10-20 02:07:20.700522 W | pkg/fileutil: check file permission: directory "/tmp/torchelastic_etcd_datackbvw11v/0" exist, but the permission is "drwxrwxr-x". The recommended permission is "-rwx------" to prevent possible unprivileged access to the data.
2025-10-20 02:07:20.702648 I | etcdserver: name = default
2025-10-20 02:07:20.702652 I | etcdserver: data dir = /tmp/torchelastic_etcd_datackbvw11v/0
2025-10-20 02:07:20.702654 I | etcdserver: member dir = /tmp/torchelastic_etcd_datackbvw11v/0/member
2025-10-20 02:07:20.702656 I | etcdserver: heartbeat = 100ms
2025-10-20 02:07:20.702657 I | etcdserver: election = 1000ms
2025-10-20 02:07:20.702659 I | etcdserver: snapshot count = 100000
2025-10-20 02:07:20.702750 I | etcdserver: advertise client URLs = http://localhost:47051
2025-10-20 02:07:20.702752 I | etcdserver: initial advertise peer URLs = http://localhost:2380
2025-10-20 02:07:20.702757 I | etcdserver: initial cluster = default=http://localhost:2380
2025-10-20 02:07:20.704497 I | etcdserver: starting member 8e9e05c52164694d in cluster cdf818194e3a8c32
2025-10-20 02:07:20.704509 I | raft: 8e9e05c52164694d became follower at term 0
2025-10-20 02:07:20.704513 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2025-10-20 02:07:20.704516 I | raft: 8e9e05c52164694d became follower at term 1
2025-10-20 02:07:20.705721 W | auth: simple token is not cryptographically signed
2025-10-20 02:07:20.707662 I | etcdserver: starting server... [version: 3.3.25, cluster version: to_be_decided]
2025-10-20 02:07:20.707703 I | etcdserver: 8e9e05c52164694d as single-node; fast-forwarding 9 ticks (election ticks 10)
2025-10-20 02:07:20.707916 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
2025-10-20 02:07:21.605173 I | raft: 8e9e05c52164694d is starting a new election at term 1
2025-10-20 02:07:21.605220 I | raft: 8e9e05c52164694d became candidate at term 2
2025-10-20 02:07:21.605232 I | raft: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 2
2025-10-20 02:07:21.605237 I | raft: 8e9e05c52164694d became leader at term 2
2025-10-20 02:07:21.605241 I | raft: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 2
2025-10-20 02:07:21.605308 I | etcdserver: setting up the initial cluster version to 3.3
2025-10-20 02:07:21.605490 N | etcdserver/membership: set the initial cluster version to 3.3
2025-10-20 02:07:21.605517 I | etcdserver/api: enabled capabilities for version 3.3
2025-10-20 02:07:21.605536 I | etcdserver: published {Name:default ClientURLs:[http://localhost:47051]} to cluster cdf818194e3a8c32
2025-10-20 02:07:21.605554 I | embed: ready to serve client requests
2025-10-20 02:07:21.605737 E | etcdmain: forgot to set Type=notify in systemd service file?
2025-10-20 02:07:21.605936 N | embed: serving insecure client requests on 127.0.0.1:47051, this is strongly discouraged!
INFO 2025-10-20 02:07:21,692 Etcd machines: ['http://localhost:47051']
/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/etcd/client.py:954: DeprecationWarning: HTTPResponse.getheader() is deprecated and will be removed in urllib3 v2.6.0. Instead use HTTPResponse.headers.get(name, default).
  cluster_id = response.getheader("x-etcd-cluster-id")
/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/etcd/__init__.py:62: DeprecationWarning: HTTPResponse.getheaders() is deprecated and will be removed in urllib3 v2.6.0. Instead access HTTPResponse.headers directly.
  headers = response.getheaders()
Exception ignored in: <function EtcdRendezvousHandler.__del__ at 0x7fc01e1795a0>
Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/etcd_rendezvous.py", line 168, in __del__
    del self._rdzv_impl
AttributeError: _rdzv_impl
2025-10-20 02:07:21.696551 N | pkg/osutil: received terminated signal, shutting down...
2025-10-20 02:07:21.696642 I | etcdserver: skipped leadership transfer for single member cluster
E
======================================================================
ERROR: test_etcd_server_with_rendezvous (etcd_server_test.EtcdServerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/xiangdong/pytorch/test/distributed/elastic/rendezvous/etcd_server_test.py", line 58, in test_etcd_server_with_rendezvous
    rdzv_handler = EtcdRendezvousHandler(rdzv)
TypeError: EtcdRendezvousHandler.__init__() missing 1 required positional argument: 'local_addr'

----------------------------------------------------------------------
Ran 2 tests in 2.018s

FAILED (errors=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.009s

OK

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.003s

OK
..........................
----------------------------------------------------------------------
Ran 26 tests in 1.332s

OK
........./home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py:100: DeprecationWarning: WorkerSpec.fn will be deprecated, please use WorkerSpec.entrypoint instead
  warnings.warn(
..W1020 02:07:29.807000 2345376 site-packages/torch/distributed/elastic/agent/server/api.py:726] Received Signals.SIGTERM death signal, shutting down workers
..........................
----------------------------------------------------------------------
Ran 37 tests in 1.677s

OK
