<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="27" time="87.687" timestamp="2025-09-12T14:18:20.837191+00:00" hostname="dut7358"><testcase classname="test.distributed.test_c10d_common.TimeoutTest" name="test_store_based_barrier" time="31.198" /><testcase classname="test.distributed.test_c10d_common.ComputeBucketAssignmentTest" name="test_multi_limit_multi_dtype" time="0.001" /><testcase classname="test.distributed.test_c10d_common.ComputeBucketAssignmentTest" name="test_multi_limit_single_dtype" time="0.001" /><testcase classname="test.distributed.test_c10d_common.ComputeBucketAssignmentTest" name="test_single_limit_multi_dtype" time="0.001" /><testcase classname="test.distributed.test_c10d_common.ComputeBucketAssignmentTest" name="test_single_limit_single_dtype" time="0.001" /><testcase classname="test.distributed.test_c10d_common.CommTest" name="test_debug_level" time="2.707" /><testcase classname="test.distributed.test_c10d_common.PythonProcessGroupExtensionTest" name="test_abort" time="3.410" /><testcase classname="test.distributed.test_c10d_common.PythonProcessGroupExtensionTest" name="test_backend_class_attr" time="2.809" /><testcase classname="test.distributed.test_c10d_common.PythonProcessGroupExtensionTest" name="test_backend_config" time="2.609"><failure message="RuntimeError: Process 0 exited with error code 10 and exception:&#10;Traceback (most recent call last):&#10;  File &quot;/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py&quot;, line 864, in run_test&#10;    getattr(self, test_name)()&#10;  File &quot;/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py&quot;, line 718, in wrapper&#10;    fn()&#10;  File &quot;/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py&quot;, line 3225, in wrapper&#10;    method(*args, **kwargs)&#10;  File &quot;/home/jenkins/actions-runner/_work/torch-xpu-ops/torch-xpu-ops/pytorch/test/distributed/test_c10d_common.py&quot;, line 1802, in test_backend_config&#10;    self.assertEqual(str(config), expected_value)&#10;  File &quot;/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py&quot;, line 4180, in assertEqual&#10;    raise error_metas.pop()[0].to_error(  # type: ignore[index]&#10;AssertionError: String comparison failed: 'cpu:dummy,cuda:dummy' != 'cpu:dummy,cuda:dummy,xpu:dummy'&#10;- cpu:dummy,cuda:dummy&#10;+ cpu:dummy,cuda:dummy,xpu:dummy&#10;?                     ++++++++++&#10;&#10;&#10;To execute this test, run the following from the base repo dir:&#10;    PYTORCH_TEST_WITH_SLOW=1 python test/distributed/test_c10d_common.py PythonProcessGroupExtensionTest.test_backend_config&#10;&#10;This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0&#10;&#10;Process 3 exited with error code 10 and exception:&#10;Traceback (most recent call last):&#10;  File &quot;/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py&quot;, line 864, in run_test&#10;    getattr(self, test_name)()&#10;  File &quot;/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py&quot;, line 718, in wrapper&#10;    fn()&#10;  File &quot;/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py&quot;, line 3225, in wrapper&#10;    method(*args, **kwargs)&#10;  File &quot;/home/jenkins/actions-runner/_work/torch-xpu-ops/torch-xpu-ops/pytorch/test/distributed/test_c10d_common.py&quot;, line 1802, in test_backend_config&#10;    self.assertEqual(str(config), expected_value)&#10;  File &quot;/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py&quot;, line 4180, in assertEqual&#10;    raise error_metas.pop()[0].to_error(  # type: ignore[index]&#10;AssertionError: String comparison failed: 'cpu:dummy,cuda:dummy' != 'cpu:dummy,cuda:dummy,xpu:dummy'&#10;- cpu:dummy,cuda:dummy&#10;+ cpu:dummy,cuda:dummy,xpu:dummy&#10;?                     ++++++++++&#10;&#10;&#10;To execute this test, run the following from the base repo dir:&#10;    PYTORCH_TEST_WITH_SLOW=1 python test/distributed/test_c10d_common.py PythonProcessGroupExtensionTest.test_backend_config&#10;&#10;This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0">Traceback (most recent call last):
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1020, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Process 0 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 864, in run_test
    getattr(self, test_name)()
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 718, in wrapper
    fn()
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3225, in wrapper
    method(*args, **kwargs)
  File "/home/jenkins/actions-runner/_work/torch-xpu-ops/torch-xpu-ops/pytorch/test/distributed/test_c10d_common.py", line 1802, in test_backend_config
    self.assertEqual(str(config), expected_value)
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4180, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: String comparison failed: 'cpu:dummy,cuda:dummy' != 'cpu:dummy,cuda:dummy,xpu:dummy'
- cpu:dummy,cuda:dummy
+ cpu:dummy,cuda:dummy,xpu:dummy
?                     ++++++++++


To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_SLOW=1 python test/distributed/test_c10d_common.py PythonProcessGroupExtensionTest.test_backend_config

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

Process 3 exited with error code 10 and exception:
Traceback (most recent call last):
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 864, in run_test
    getattr(self, test_name)()
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 718, in wrapper
    fn()
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 3225, in wrapper
    method(*args, **kwargs)
  File "/home/jenkins/actions-runner/_work/torch-xpu-ops/torch-xpu-ops/pytorch/test/distributed/test_c10d_common.py", line 1802, in test_backend_config
    self.assertEqual(str(config), expected_value)
  File "/tmp/xpu-tool/Python/3.10.18/x64/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4180, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: String comparison failed: 'cpu:dummy,cuda:dummy' != 'cpu:dummy,cuda:dummy,xpu:dummy'
- cpu:dummy,cuda:dummy
+ cpu:dummy,cuda:dummy,xpu:dummy
?                     ++++++++++


To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_SLOW=1 python test/distributed/test_c10d_common.py PythonProcessGroupExtensionTest.test_backend_config

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0</failure></testcase><testcase classname="test.distributed.test_c10d_common.PythonProcessGroupExtensionTest" name="test_canonicalize_helper" time="3.209" /><testcase classname="test.distributed.test_c10d_common.PythonProcessGroupExtensionTest" name="test_collectives" time="3.210" /><testcase classname="test.distributed.test_c10d_common.PythonProcessGroupExtensionTest" name="test_get_backend_name" time="2.909" /><testcase classname="test.distributed.test_c10d_common.PythonProcessGroupExtensionTest" name="test_init_process_group_with_multiple_backends" time="2.909" /><testcase classname="test.distributed.test_c10d_common.PythonProcessGroupExtensionTest" name="test_is_backend_available" time="2.909" /><testcase classname="test.distributed.test_c10d_common.PythonProcessGroupExtensionTest" name="test_send_recv" time="3.310" /><testcase classname="test.distributed.test_c10d_common.PythonProcessGroupExtensionTest" name="test_shutdown" time="3.410" /><testcase classname="test.distributed.test_c10d_common.ProcessGroupWithDispatchedCollectivesTests" name="test_default_process_group" time="4.008" /><testcase classname="test.distributed.test_c10d_common.ProcessGroupWithDispatchedCollectivesTests" name="test_init_process_group_for_all_backends" time="2.906" /><testcase classname="test.distributed.test_c10d_common.ProcessGroupWithDispatchedCollectivesTests" name="test_init_process_group_optional_backend" time="2.606" /><testcase classname="test.distributed.test_c10d_common.ReduceOpTest" name="test_op_isinstance_of_reduceop" time="0.001" /><testcase classname="test.distributed.test_c10d_common.ReduceOpTest" name="test_reduceop_copyable" time="0.002" /><testcase classname="test.distributed.test_c10d_common.ReduceOpTest" name="test_reduceop_equal" time="0.002" /><testcase classname="test.distributed.test_c10d_common.ReduceOpTest" name="test_reduceop_pickle" time="0.003" /><testcase classname="test.distributed.test_c10d_common.LocalRankTest" name="testNodeLocalRank" time="3.009" /><testcase classname="test.distributed.test_c10d_common.LocalRankTest" name="testNodeLocalRankOverridesFallback" time="2.809" /><testcase classname="test.distributed.test_c10d_common.LocalRankTest" name="testWithoutEnv" time="2.908" /><testcase classname="test.distributed.test_c10d_common.LocalRankTest" name="testWithoutEnvWithFallback" time="2.908" /></testsuite></testsuites>