<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="14" skipped="0" tests="14" time="52.096" timestamp="2025-08-22T09:09:32.854285" hostname="dut7358"><testcase classname="test.distributed.fsdp.test_fsdp_flatten_params.TestFlattenParams" name="test_empty_module" time="4.293"><failure message="AssertionError: Scalars are not equal!&#10;&#10;Expected 0 but got -11.&#10;Absolute difference: 11&#10;Relative difference: inf&#10;Expected exit code 0 but got -11 for pid: 127395">Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1056, in _check_return_codes
    self.assertEqual(
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 0 but got -11.
Absolute difference: 11
Relative difference: inf
Expected exit code 0 but got -11 for pid: 127395</failure></testcase><testcase classname="test.distributed.fsdp.test_fsdp_flatten_params.TestFlattenParams" name="test_flat_param_shard_metadata_aligned_full_precision" time="4.216"><failure message="AssertionError: Scalars are not equal!&#10;&#10;Expected 0 but got -11.&#10;Absolute difference: 11&#10;Relative difference: inf&#10;Expected exit code 0 but got -11 for pid: 127469">Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1056, in _check_return_codes
    self.assertEqual(
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 0 but got -11.
Absolute difference: 11
Relative difference: inf
Expected exit code 0 but got -11 for pid: 127469</failure></testcase><testcase classname="test.distributed.fsdp.test_fsdp_flatten_params.TestFlattenParams" name="test_flat_param_shard_metadata_aligned_mixed_precision" time="3.312"><failure message="AssertionError: Scalars are not equal!&#10;&#10;Expected 0 but got -11.&#10;Absolute difference: 11&#10;Relative difference: inf&#10;Expected exit code 0 but got -11 for pid: 127543">Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1056, in _check_return_codes
    self.assertEqual(
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 0 but got -11.
Absolute difference: 11
Relative difference: inf
Expected exit code 0 but got -11 for pid: 127543</failure></testcase><testcase classname="test.distributed.fsdp.test_fsdp_flatten_params.TestFlattenParams" name="test_flat_param_shard_metadata_unaligned" time="3.611"><failure message="AssertionError: Scalars are not equal!&#10;&#10;Expected 0 but got -11.&#10;Absolute difference: 11&#10;Relative difference: inf&#10;Expected exit code 0 but got -11 for pid: 127617">Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1056, in _check_return_codes
    self.assertEqual(
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 0 but got -11.
Absolute difference: 11
Relative difference: inf
Expected exit code 0 but got -11 for pid: 127617</failure></testcase><testcase classname="test.distributed.fsdp.test_fsdp_flatten_params.TestFlattenParams" name="test_flat_param_shard_metadata_with_memory_format_memory_format0" time="3.213"><failure message="AssertionError: Scalars are not equal!&#10;&#10;Expected 0 but got -11.&#10;Absolute difference: 11&#10;Relative difference: inf&#10;Expected exit code 0 but got -11 for pid: 127691">Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1056, in _check_return_codes
    self.assertEqual(
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 0 but got -11.
Absolute difference: 11
Relative difference: inf
Expected exit code 0 but got -11 for pid: 127691</failure></testcase><testcase classname="test.distributed.fsdp.test_fsdp_flatten_params.TestFlattenParams" name="test_flat_param_shard_metadata_with_memory_format_memory_format1" time="3.212"><failure message="AssertionError: Scalars are not equal!&#10;&#10;Expected 0 but got -11.&#10;Absolute difference: 11&#10;Relative difference: inf&#10;Expected exit code 0 but got -11 for pid: 127766">Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1056, in _check_return_codes
    self.assertEqual(
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 0 but got -11.
Absolute difference: 11
Relative difference: inf
Expected exit code 0 but got -11 for pid: 127766</failure></testcase><testcase classname="test.distributed.fsdp.test_fsdp_flatten_params.TestFlattenParams" name="test_flatten_nothing" time="3.313"><failure message="AssertionError: Scalars are not equal!&#10;&#10;Expected 0 but got -11.&#10;Absolute difference: 11&#10;Relative difference: inf&#10;Expected exit code 0 but got -11 for pid: 127840">Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1056, in _check_return_codes
    self.assertEqual(
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 0 but got -11.
Absolute difference: 11
Relative difference: inf
Expected exit code 0 but got -11 for pid: 127840</failure></testcase><testcase classname="test.distributed.fsdp.test_fsdp_flatten_params.TestFlattenParams" name="test_numel_with_shared_params" time="3.312"><failure message="AssertionError: Scalars are not equal!&#10;&#10;Expected 0 but got -11.&#10;Absolute difference: 11&#10;Relative difference: inf&#10;Expected exit code 0 but got -11 for pid: 127914">Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1056, in _check_return_codes
    self.assertEqual(
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 0 but got -11.
Absolute difference: 11
Relative difference: inf
Expected exit code 0 but got -11 for pid: 127914</failure></testcase><testcase classname="test.distributed.fsdp.test_fsdp_flatten_params.TestFlattenParams" name="test_numel_without_shared_params" time="3.211"><failure message="AssertionError: Scalars are not equal!&#10;&#10;Expected 0 but got -11.&#10;Absolute difference: 11&#10;Relative difference: inf&#10;Expected exit code 0 but got -11 for pid: 127988">Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1056, in _check_return_codes
    self.assertEqual(
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 0 but got -11.
Absolute difference: 11
Relative difference: inf
Expected exit code 0 but got -11 for pid: 127988</failure></testcase><testcase classname="test.distributed.fsdp.test_fsdp_flatten_params.TestFlattenParams" name="test_output_with_shared_params" time="3.313"><failure message="AssertionError: Scalars are not equal!&#10;&#10;Expected 0 but got -11.&#10;Absolute difference: 11&#10;Relative difference: inf&#10;Expected exit code 0 but got -11 for pid: 128062">Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1056, in _check_return_codes
    self.assertEqual(
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 0 but got -11.
Absolute difference: 11
Relative difference: inf
Expected exit code 0 but got -11 for pid: 128062</failure></testcase><testcase classname="test.distributed.fsdp.test_fsdp_flatten_params.TestFlattenParams" name="test_output_without_shared_params" time="3.214"><failure message="AssertionError: Scalars are not equal!&#10;&#10;Expected 0 but got -11.&#10;Absolute difference: 11&#10;Relative difference: inf&#10;Expected exit code 0 but got -11 for pid: 128136">Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1056, in _check_return_codes
    self.assertEqual(
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 0 but got -11.
Absolute difference: 11
Relative difference: inf
Expected exit code 0 but got -11 for pid: 128136</failure></testcase><testcase classname="test.distributed.fsdp.test_fsdp_flatten_params.TestFlattenParams" name="test_partial_flattening" time="3.413"><failure message="AssertionError: Scalars are not equal!&#10;&#10;Expected 0 but got -11.&#10;Absolute difference: 11&#10;Relative difference: inf&#10;Expected exit code 0 but got -11 for pid: 128210">Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1056, in _check_return_codes
    self.assertEqual(
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 0 but got -11.
Absolute difference: 11
Relative difference: inf
Expected exit code 0 but got -11 for pid: 128210</failure></testcase><testcase classname="test.distributed.fsdp.test_fsdp_flatten_params.TestFlattenParams" name="test_pnorm_after_step_with_shared_params" time="3.212"><failure message="AssertionError: Scalars are not equal!&#10;&#10;Expected 0 but got -11.&#10;Absolute difference: 11&#10;Relative difference: inf&#10;Expected exit code 0 but got -11 for pid: 128284">Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1056, in _check_return_codes
    self.assertEqual(
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 0 but got -11.
Absolute difference: 11
Relative difference: inf
Expected exit code 0 but got -11 for pid: 128284</failure></testcase><testcase classname="test.distributed.fsdp.test_fsdp_flatten_params.TestFlattenParams" name="test_writeback_orig_params_no_shard" time="3.213"><failure message="AssertionError: Scalars are not equal!&#10;&#10;Expected 0 but got -11.&#10;Absolute difference: 11&#10;Relative difference: inf&#10;Expected exit code 0 but got -11 for pid: 128358">Traceback (most recent call last):
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 716, in wrapper
    self._join_processes(fn)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 980, in _join_processes
    self._check_return_codes(fn, elapsed_time)
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_distributed.py", line 1056, in _check_return_codes
    self.assertEqual(
  File "/home/jenkins/.conda/envs/xpu_op_/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 4181, in assertEqual
    raise error_metas.pop()[0].to_error(  # type: ignore[index]
AssertionError: Scalars are not equal!

Expected 0 but got -11.
Absolute difference: 11
Relative difference: inf
Expected exit code 0 but got -11 for pid: 128358</failure></testcase></testsuite></testsuites>